/**
 * RoofRex Embeddable Chat Widget — by Sheikh AI Agency
 * ─────────────────────────────────────────────────────
 * HOW TO INSTALL ON A CLIENT'S SITE (paste before </body>):
 *
 * <script>
 *   window.RoofRexConfig = {
 *     companyName: "Apex Roofing Co.",       // required
 *     whatsappNumber: "10000000000",         // required — digits only, country code, no + or spaces
 *     apiEndpoint: "https://sheikh-ai-proxy.vercel.app/api/chat-roofrex", // required
 *     botName: "Rex",                        // optional — default "Rex"
 *     botLetter: "R",                        // optional — default first letter of botName
 *     primaryColor: "#c1502e",               // optional — default rust
 *     primaryColorLight: "#e07a4f"           // optional — default light rust
 *   };
 * </script>
 * <script src="https://sheikh-ai-proxy.vercel.app/roofrex-widget.js"></script>
 *
 * That's it — nothing else to touch. Every client gets their own config block,
 * same widget file. Do NOT edit this file per client — edit the config block instead.
 */
(function(){
  const CFG = Object.assign({
    companyName: "Your Roofing Company",
    whatsappNumber: "10000000000",
    apiEndpoint: "",
    botName: "Rex",
    botLetter: "",
    primaryColor: "#c1502e",
    primaryColorLight: "#e07a4f"
  }, window.RoofRexConfig || {});
  CFG.botLetter = CFG.botLetter || CFG.botName.charAt(0).toUpperCase();

  if(!CFG.apiEndpoint){
    console.warn("RoofRex widget: no apiEndpoint set in window.RoofRexConfig — typed questions will use the fallback reply only.");
  }

  // ── INJECT FONTS + STYLES (prefixed rrx- to avoid clashing with host site CSS) ──
  const fontLink = document.createElement('link');
  fontLink.rel = 'stylesheet';
  fontLink.href = 'https://fonts.googleapis.com/css2?family=Oswald:wght@500;600;700&family=Inter:wght@400;500;600&display=swap';
  document.head.appendChild(fontLink);

  const style = document.createElement('style');
  style.textContent = `
  .rrx-root, .rrx-root * { box-sizing:border-box; }
  .rrx-root{
    position:fixed; z-index:999999; bottom:20px; right:20px;
    font-family:'Inter',sans-serif;
  }
  .rrx-bubble{
    width:62px; height:62px; border-radius:50%;
    background:linear-gradient(135deg, ${CFG.primaryColor}, ${CFG.primaryColorLight});
    display:flex; align-items:center; justify-content:center;
    cursor:pointer; box-shadow:0 8px 28px rgba(0,0,0,0.35);
    transition:transform .18s ease; border:none; position:relative;
  }
  .rrx-bubble:hover{ transform:scale(1.06); }
  .rrx-bubble svg{ width:28px; height:28px; }
  .rrx-bubble .rrx-dot{
    position:absolute; top:2px; right:2px; width:14px; height:14px;
    background:#22c55e; border-radius:50%; border:2.5px solid #17181a;
    animation:rrxPulse 2s infinite;
  }
  @keyframes rrxPulse{ 0%,100%{transform:scale(1);opacity:1} 50%{transform:scale(1.25);opacity:.7} }

  .rrx-panel{
    position:absolute; bottom:76px; right:0;
    width:370px; max-width:calc(100vw - 24px); height:560px; max-height:calc(100vh - 110px);
    background:#faf8f5; border-radius:18px; overflow:hidden;
    box-shadow:0 24px 64px rgba(0,0,0,0.4), 0 0 0 1px rgba(0,0,0,0.06);
    display:none; flex-direction:column;
    opacity:0; transform:translateY(16px) scale(0.98);
    transition:opacity .22s ease, transform .22s ease;
  }
  .rrx-panel.rrx-open{ display:flex; opacity:1; transform:translateY(0) scale(1); }

  .rrx-header{
    background:linear-gradient(135deg, #1a1c1e, #2f3337);
    padding:14px 14px 14px 16px; display:flex; align-items:center; gap:11px;
    border-bottom:1px solid rgba(255,255,255,0.08); flex-shrink:0;
  }
  .rrx-avatar{
    width:36px; height:36px; border-radius:50%;
    background:linear-gradient(135deg, ${CFG.primaryColor}, ${CFG.primaryColorLight});
    display:flex; align-items:center; justify-content:center;
    font-family:'Oswald',sans-serif; font-weight:600; color:#fff; font-size:15px;
    flex-shrink:0; position:relative;
  }
  .rrx-avatar .rrx-online{
    position:absolute; width:9px; height:9px; background:#22c55e; border-radius:50%;
    border:2px solid #1a1c1e; bottom:-1px; right:-1px;
  }
  .rrx-hname{ color:#fff; font-size:14px; font-weight:600; }
  .rrx-hrole{ color:rgba(255,255,255,0.5); font-size:11px; margin-top:1px; }
  .rrx-close{
    margin-left:auto; width:28px; height:28px; border-radius:50%; border:none;
    background:rgba(255,255,255,0.08); cursor:pointer; display:flex; align-items:center; justify-content:center;
  }
  .rrx-close:hover{ background:rgba(255,255,255,0.16); }
  .rrx-close svg{ width:13px; height:13px; }

  .rrx-messages{
    flex:1; overflow-y:auto; padding:14px 11px; display:flex; flex-direction:column; gap:9px;
    scroll-behavior:smooth; background:#faf8f5;
  }
  .rrx-messages::-webkit-scrollbar{ width:3px; }
  .rrx-messages::-webkit-scrollbar-thumb{ background:#e6e0d8; border-radius:2px; }

  .rrx-row-bot{ display:flex; gap:7px; align-items:flex-end; }
  .rrx-row-user{ display:flex; justify-content:flex-end; }
  .rrx-mini-av{
    width:24px; height:24px; border-radius:50%; flex-shrink:0;
    background:linear-gradient(135deg, ${CFG.primaryColor}, ${CFG.primaryColorLight});
    display:flex; align-items:center; justify-content:center;
    font-family:'Oswald',sans-serif; font-size:10px; color:#fff; font-weight:600;
  }
  .rrx-bubble-bot{
    background:#fff; border-radius:13px 13px 13px 3px; padding:9px 12px;
    font-size:13px; color:#1a1c1e; line-height:1.5; max-width:230px;
    box-shadow:0 2px 8px rgba(0,0,0,.06); border:1px solid #ece6dc;
  }
  .rrx-bubble-user{
    background:linear-gradient(135deg,#1a1c1e,#2f3337); color:#fff;
    border-radius:13px 13px 3px 13px; padding:9px 12px; font-size:13px; line-height:1.5; max-width:190px;
  }

  .rrx-qr{ display:flex; flex-wrap:wrap; gap:6px; padding-left:31px; }
  .rrx-qr-btn{
    background:#fff; border:1.5px solid ${CFG.primaryColor}; color:#1a1c1e;
    border-radius:16px; padding:5px 11px; font-size:11.5px; font-weight:500;
    cursor:pointer; font-family:'Inter',sans-serif; transition:all .15s;
  }
  .rrx-qr-btn:hover, .rrx-qr-btn.rrx-active{ background:${CFG.primaryColor}; color:#fff; }
  .rrx-qr-btn:disabled{ opacity:.4; cursor:default; }

  .rrx-card{
    background:#fff; border-radius:11px; padding:12px; max-width:235px;
    border:1px solid #ece6dc; margin-left:31px; box-shadow:0 2px 8px rgba(0,0,0,.06);
  }
  .rrx-card-title{ font-size:11px; font-weight:600; color:#1a1c1e; margin-bottom:7px; display:flex; align-items:center; gap:5px; }
  .rrx-card-title::before{ content:''; width:3px; height:12px; background:${CFG.primaryColor}; border-radius:2px; }
  .rrx-slots{ display:grid; grid-template-columns:1fr 1fr; gap:5px; margin-bottom:8px; }
  .rrx-slot{
    background:#faf8f5; border:1.5px solid #ece6dc; border-radius:7px; padding:6px 4px;
    font-size:10.5px; text-align:center; cursor:pointer; color:#1a1c1e; font-weight:500; line-height:1.4;
  }
  .rrx-slot:hover, .rrx-slot.rrx-sel{ background:#f5e2d8; border-color:${CFG.primaryColor}; }
  .rrx-confirm-btn{
    width:100%; background:#1a1c1e; color:#fff; border:none; border-radius:8px; padding:8px;
    font-size:11.5px; font-weight:600; cursor:pointer; font-family:'Inter',sans-serif;
  }
  .rrx-confirm-btn:hover{ background:${CFG.primaryColor}; }

  .rrx-lead input{
    width:100%; background:#faf8f5; border:1.5px solid #ece6dc; color:#1a1c1e;
    padding:8px 10px; border-radius:7px; font-size:12.5px; font-family:'Inter',sans-serif;
    outline:none; margin-bottom:7px;
  }
  .rrx-lead input:focus{ border-color:${CFG.primaryColor}; }
  .rrx-lead-submit{
    width:100%; background:${CFG.primaryColor}; color:#fff; border:none; padding:9px;
    border-radius:8px; font-weight:600; font-size:12.5px; cursor:pointer; font-family:'Inter',sans-serif;
  }
  .rrx-lead-submit:hover{ background:${CFG.primaryColorLight}; }

  .rrx-confirmed{
    background:linear-gradient(135deg,#1a1c1e,#2f3337); border-radius:11px; padding:13px; color:#fff;
    max-width:225px; margin-left:31px; border:1px solid rgba(193,80,46,.3);
  }
  .rrx-confirmed .rrx-cc-tag{ color:${CFG.primaryColorLight}; font-size:10px; font-weight:600; margin-bottom:4px; text-transform:uppercase; letter-spacing:.4px; }
  .rrx-confirmed .rrx-cc-title{ font-family:'Oswald',sans-serif; font-size:14px; margin-bottom:4px; }
  .rrx-confirmed .rrx-cc-detail{ font-size:10.5px; opacity:.8; line-height:1.6; }

  .rrx-wa{
    background:#fff; border-radius:11px; padding:12px; max-width:225px; border:1px solid #ece6dc; margin-left:31px;
  }
  .rrx-wa-title{ font-size:12px; font-weight:600; color:#1a1c1e; margin-bottom:2px; }
  .rrx-wa-sub{ font-size:10.5px; color:#777; line-height:1.5; margin-bottom:8px; }
  .rrx-wa-btn{
    display:flex; align-items:center; gap:7px; background:#25d366; color:#fff; border:none;
    border-radius:8px; padding:8px 11px; font-size:11.5px; font-weight:600; cursor:pointer; width:100%;
  }
  .rrx-wa-btn:hover{ background:#20ba5a; }

  .rrx-typing{ display:flex; gap:7px; align-items:flex-end; }
  .rrx-typing-dots{ background:#fff; border-radius:13px 13px 13px 3px; padding:10px 13px; display:flex; gap:4px; border:1px solid #ece6dc; }
  .rrx-tdot{ width:5px; height:5px; border-radius:50%; background:${CFG.primaryColor}; animation:rrxBop 1.2s infinite; }
  .rrx-tdot:nth-child(2){ animation-delay:.2s; }
  .rrx-tdot:nth-child(3){ animation-delay:.4s; }
  @keyframes rrxBop{ 0%,60%,100%{transform:translateY(0)} 30%{transform:translateY(-4px)} }

  .rrx-input-area{ padding:9px 10px; background:#fff; border-top:1px solid #ece6dc; display:flex; gap:7px; align-items:center; flex-shrink:0; }
  .rrx-input{
    flex:1; border:1.5px solid #ece6dc; border-radius:18px; padding:8px 13px; font-size:12.5px;
    font-family:'Inter',sans-serif; outline:none; color:#1a1c1e; background:#faf8f5;
  }
  .rrx-input:focus{ border-color:${CFG.primaryColor}; background:#fff; }
  .rrx-send{
    width:32px; height:32px; border-radius:50%; background:#1a1c1e; border:none; cursor:pointer;
    display:flex; align-items:center; justify-content:center; flex-shrink:0;
  }
  .rrx-send:hover{ background:${CFG.primaryColor}; }
  .rrx-send svg{ width:12px; height:12px; fill:#fff; }

  .rrx-footer{ padding:5px 10px; background:#fff; border-top:1px solid #ece6dc; text-align:center; font-size:9.5px; color:#bbb; flex-shrink:0; }
  .rrx-footer span{ color:${CFG.primaryColor}; font-weight:600; }

  @media (max-width:480px){
    .rrx-panel{ width:calc(100vw - 20px); height:calc(100vh - 100px); bottom:76px; right:-2px; }
  }
  `;
  document.head.appendChild(style);

  // ── INJECT DOM ──
  const root = document.createElement('div');
  root.className = 'rrx-root';
  root.innerHTML = `
    <button class="rrx-bubble" id="rrxBubble" aria-label="Open chat">
      <span class="rrx-dot"></span>
      <svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <path d="M2 11L12 4L22 11"/><path d="M4 10V20H20V10"/>
      </svg>
    </button>
    <div class="rrx-panel" id="rrxPanel">
      <div class="rrx-header">
        <div class="rrx-avatar">${CFG.botLetter}<span class="rrx-online"></span></div>
        <div>
          <div class="rrx-hname">${CFG.botName}</div>
          <div class="rrx-hrole">AI Roofing Assistant · ${CFG.companyName}</div>
        </div>
        <button class="rrx-close" id="rrxClose" aria-label="Close chat">
          <svg viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
        </button>
      </div>
      <div class="rrx-messages" id="rrxMsgs"></div>
      <div class="rrx-input-area">
        <input class="rrx-input" id="rrxInp" placeholder="Ask ${CFG.botName} anything…" />
        <button class="rrx-send" id="rrxSendBtn">
          <svg viewBox="0 0 24 24"><path d="M2 21L23 12 2 3v7l15 2-15 2z"/></svg>
        </button>
      </div>
      <div class="rrx-footer">Powered by <span>Sheikh AI Agency</span></div>
    </div>
  `;
  document.body.appendChild(root);

  // ── LOGIC ──
  let history=[], selectedSlot=null, selectedService=null, opened=false;
  let lead={name:'',phone:'',email:''}, leadStep=null;
  const $msgs = () => document.getElementById('rrxMsgs');
  const scrollDown = () => { const m=$msgs(); m.scrollTop=m.scrollHeight; };

  function addEl(html, delay=0){
    return new Promise(r=>setTimeout(()=>{
      const d=document.createElement('div'); d.innerHTML=html; $msgs().appendChild(d); scrollDown(); r();
    }, delay));
  }
  function botMsg(text, delay=0){
    return addEl(`<div class="rrx-row-bot"><div class="rrx-mini-av">${CFG.botLetter}</div><div class="rrx-bubble-bot">${text}</div></div>`, delay);
  }
  function userMsg(text){
    const d=document.createElement('div');
    d.innerHTML=`<div class="rrx-row-user"><div class="rrx-bubble-user">${text}</div></div>`;
    $msgs().appendChild(d); scrollDown();
  }
  function showTyping(delay=0){
    return new Promise(r=>setTimeout(()=>{
      const d=document.createElement('div'); d.id='rrxTyp';
      d.innerHTML=`<div class="rrx-typing"><div class="rrx-mini-av">${CFG.botLetter}</div><div class="rrx-typing-dots"><div class="rrx-tdot"></div><div class="rrx-tdot"></div><div class="rrx-tdot"></div></div></div>`;
      $msgs().appendChild(d); scrollDown(); r();
    }, delay));
  }
  function removeTyping(){ const t=document.getElementById('rrxTyp'); if(t) t.remove(); }

  function showQR(buttons){
    const old=document.getElementById('rrxQr'); if(old) old.remove();
    const d=document.createElement('div'); d.id='rrxQr';
    d.innerHTML=`<div class="rrx-qr">${buttons.map(b=>`<button class="rrx-qr-btn" data-label="${b}">${b}</button>`).join('')}</div>`;
    $msgs().appendChild(d); scrollDown();
    d.querySelectorAll('.rrx-qr-btn').forEach(btn=>{
      btn.onclick = ()=>{ qrPick(btn.dataset.label); };
    });
  }
  function disableQR(chosen){
    document.querySelectorAll('.rrx-qr-btn').forEach(b=>{
      b.disabled=true; if(b.dataset.label===chosen) b.classList.add('rrx-active');
    });
  }

  async function getAI(userText){
    history.push({role:'user',content:userText});
    if(!CFG.apiEndpoint){
      return "Thanks for your message! For immediate help, tap WhatsApp Us below.";
    }
    try{
      const res=await fetch(CFG.apiEndpoint,{
        method:'POST', headers:{'Content-Type':'application/json'},
        body:JSON.stringify({message:userText,conversationHistory:history})
      });
      const data=await res.json();
      const reply=data.response||"I'd love to help! Could you share a bit more detail?";
      history.push({role:'assistant',content:reply});
      return reply;
    }catch(err){
      console.error('RoofRex widget API error:', err);
      return "Thanks for your message! For immediate help, tap WhatsApp Us below.";
    }
  }

  async function startLeadCapture(){
    leadStep='name';
    await botMsg("Before I confirm your inspection, may I take a few quick details?");
    await new Promise(r=>setTimeout(r,450));
    await botMsg("What is your full name?");
    document.getElementById('rrxInp').placeholder="Type your full name…";
    document.getElementById('rrxInp').focus();
  }

  async function handleLeadStep(text){
    if(leadStep==='name'){
      if(text.trim().length<2){ await botMsg("Could you share your full name please?"); return; }
      lead.name=text.trim(); leadStep='phone';
      await botMsg(`Thanks, ${lead.name}!`);
      await new Promise(r=>setTimeout(r,350));
      await botMsg("Best phone number to reach you?");
      document.getElementById('rrxInp').placeholder="e.g. (000) 000-0000";
    } else if(leadStep==='phone'){
      const digits=text.replace(/\D/g,'');
      if(digits.length<7){ await botMsg("That doesn't look like a valid phone number — try again?"); return; }
      lead.phone=text.trim(); leadStep='email';
      await botMsg("Got it! And your email?");
      document.getElementById('rrxInp').placeholder="e.g. john@example.com";
    } else if(leadStep==='email'){
      const ok=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(text.trim());
      if(!ok){ await botMsg("That doesn't look like a valid email — e.g. john@gmail.com"); return; }
      lead.email=text.trim(); leadStep=null;
      document.getElementById('rrxInp').placeholder=`Ask ${CFG.botName} anything…`;
      await showLeadConfirmed();
    }
  }

  async function showLeadConfirmed(){
    await showTyping(150); await new Promise(r=>setTimeout(r,700)); removeTyping();
    const d=document.createElement('div');
    d.innerHTML=`<div class="rrx-confirmed">
      <div class="rrx-cc-tag">Details Received</div>
      <div class="rrx-cc-title">Thank you, ${lead.name}!</div>
      <div class="rrx-cc-detail">
        Phone: ${lead.phone}<br>Email: ${lead.email}<br>
        ${selectedService?'Service: '+selectedService+'<br>':''}
        ${selectedSlot?'Inspection: '+selectedSlot+'<br>':''}<br>
        We'll confirm within 30 minutes during business hours.
      </div>
    </div>`;
    $msgs().appendChild(d); scrollDown();
    await new Promise(r=>setTimeout(r,600));
    await botMsg(`Thanks for choosing ${CFG.companyName}! Anything else I can help with?`);
    showQR(['No, thank you!','WhatsApp Us','Ask a Question']);
  }

  const serviceInfo = {
    'Storm Damage Repair': "Storm damage isn't always visible from the ground. Our free inspection tells you exactly what's going on, no obligation.",
    'Full Roof Replacement': "A full replacement gives you a warrantied roof built to last decades. Pricing depends on size and material, assessed free.",
    'Roof Inspection': "Our inspections are completely free, take about 20 minutes, and come with a written report — no pressure.",
    'Gutter Repair & Guards': "We repair, replace, and install guards that cut down on cleaning for good.",
    'Emergency Leak Repair': "Active leak? We offer same-day response — I can flag this as urgent right now.",
    'Metal Roofing': "Metal roofing lasts 40-70 years and handles severe weather better than asphalt."
  };

  async function qrPick(label){
    disableQR(label); userMsg(label);
    if(label==='Book an Inspection'||label==='Yes, book me in!'){ await bookingFlow(); return; }
    if(label==='WhatsApp Us'){ await waFlow(); return; }
    if(label==='No, thank you!'){ await botMsg("You're welcome! Stay dry out there."); return; }
    if(label==='Ask a Question'||label==='Ask Another Question'){ await botMsg("Of course! Type your question below."); return; }

    selectedService=label;
    await showTyping(150); await new Promise(r=>setTimeout(r,750)); removeTyping();
    await botMsg(serviceInfo[label]||"Great question! Our team can help you sort that out.");
    await new Promise(r=>setTimeout(r,350));
    await botMsg("Want to book a free inspection?");
    showQR(['Yes, book me in!','Ask a Question','WhatsApp Us']);
  }

  async function bookingFlow(){
    await showTyping(150); await new Promise(r=>setTimeout(r,750)); removeTyping();
    await botMsg("Here are our next available slots:");
    const d=document.createElement('div');
    d.innerHTML=`<div class="rrx-card">
      <div class="rrx-card-title">Available This Week</div>
      <div class="rrx-slots">
        <div class="rrx-slot" data-t="Mon 9:00 AM">Mon<br><strong>9:00 AM</strong></div>
        <div class="rrx-slot" data-t="Mon 3:00 PM">Mon<br><strong>3:00 PM</strong></div>
        <div class="rrx-slot" data-t="Tue 10:30 AM">Tue<br><strong>10:30 AM</strong></div>
        <div class="rrx-slot" data-t="Wed 2:00 PM">Wed<br><strong>2:00 PM</strong></div>
        <div class="rrx-slot" data-t="Thu 11:00 AM">Thu<br><strong>11:00 AM</strong></div>
        <div class="rrx-slot" data-t="Fri 9:30 AM">Fri<br><strong>9:30 AM</strong></div>
      </div>
      <button class="rrx-confirm-btn">Confirm Inspection →</button>
    </div>`;
    $msgs().appendChild(d); scrollDown();
    d.querySelectorAll('.rrx-slot').forEach(s=>{
      s.onclick = ()=>{
        d.querySelectorAll('.rrx-slot').forEach(x=>x.classList.remove('rrx-sel'));
        s.classList.add('rrx-sel'); selectedSlot=s.dataset.t;
      };
    });
    d.querySelector('.rrx-confirm-btn').onclick = async ()=>{
      if(!selectedSlot){ return; }
      await startLeadCapture();
    };
  }

  async function waFlow(){
    await showTyping(150); await new Promise(r=>setTimeout(r,600)); removeTyping();
    const d=document.createElement('div');
    d.innerHTML=`<div class="rrx-wa">
      <div class="rrx-wa-title">Continue on WhatsApp</div>
      <div class="rrx-wa-sub">We usually respond within 10 minutes.</div>
      <button class="rrx-wa-btn">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="white"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347z"/><path d="M12 0C5.373 0 0 5.373 0 12c0 2.138.563 4.14 1.535 5.875L.057 23.5l5.782-1.516A11.95 11.95 0 0012 24c6.627 0 12-5.373 12-12S18.627 0 12 0zm0 21.75a9.697 9.697 0 01-4.95-1.355l-.355-.211-3.676.964.98-3.585-.232-.368A9.697 9.697 0 012.25 12C2.25 6.615 6.615 2.25 12 2.25S21.75 6.615 21.75 12 17.385 21.75 12 21.75z"/></svg>
        Chat on WhatsApp
      </button>
    </div>`;
    $msgs().appendChild(d); scrollDown();
    d.querySelector('.rrx-wa-btn').onclick = ()=>{
      window.open(`https://wa.me/${CFG.whatsappNumber}?text=Hi%20${encodeURIComponent(CFG.companyName)}%2C%20I%20would%20like%20to%20enquire%20about%20a%20roof%20issue.`,'_blank');
    };
  }

  async function send(){
    const inp=document.getElementById('rrxInp');
    const text=inp.value.trim(); if(!text) return;
    inp.value=''; userMsg(text);
    const old=document.getElementById('rrxQr'); if(old) old.remove();
    if(leadStep){
      const isQuestion = text.includes('?') || /^(who|what|where|when|how|why|tell|can|do|does|is|are|i need|help)/i.test(text);
      if(isQuestion && leadStep==='name'){
        await showTyping(150); await new Promise(r=>setTimeout(r,1000)); removeTyping();
        const reply=await getAI(text); await botMsg(reply);
        await new Promise(r=>setTimeout(r,350));
        await botMsg("Now, to complete your booking — what is your full name?");
        document.getElementById('rrxInp').placeholder="Type your full name…";
        return;
      }
      await handleLeadStep(text); return;
    }
    await showTyping(150); await new Promise(r=>setTimeout(r,1100)); removeTyping();
    const reply=await getAI(text); await botMsg(reply);
    await new Promise(r=>setTimeout(r,350));
    showQR(['Book an Inspection','WhatsApp Us','Ask Another Question']);
  }

  async function openWidget(){
    document.getElementById('rrxPanel').classList.add('rrx-open');
    document.getElementById('rrxBubble').style.display='none';
    if(opened) return;
    opened=true;
    await botMsg(`Hey there! Welcome to ${CFG.companyName}.`, 500);
    await botMsg(`I'm ${CFG.botName}, your AI Roofing Assistant. How can I help you today?`, 900);
    setTimeout(()=>{
      showQR(['Storm Damage Repair','Full Roof Replacement','Roof Inspection','Gutter Repair & Guards','Emergency Leak Repair','Metal Roofing','Book an Inspection','WhatsApp Us']);
    }, 500);
  }

  document.getElementById('rrxBubble').onclick = openWidget;
  document.getElementById('rrxClose').onclick = ()=>{
    document.getElementById('rrxPanel').classList.remove('rrx-open');
    document.getElementById('rrxBubble').style.display='flex';
  };
  document.getElementById('rrxSendBtn').onclick = send;
  document.getElementById('rrxInp').addEventListener('keydown', e=>{ if(e.key==='Enter') send(); });
})();
